### ISSUE TITLE
P52 - Wifi card - BCM94352Z Lenovo 04x6020 - deleted

### ISSUE THREAD

**Issue by c3o8k1g** [midi1996/P50-opencore-hackintosh#4]
Issue deleted - not related to this repository.

**Comment by midi1996** [comment]
this could be a faulty card. FYI, the lenovo card is an E Key and the P50 is an A slot and thus you will have to dremel that notch into the card, which might break it if not properly done. Also disable LAN/WLAN switching in your bios, it makes no sense since usually windows will disconnect from it after a while. Technically DW1560 is the same chipset just lenovo rebranded. You can try this but im not sure if its going to help: update your bios (version 1.62 is the latest as of now), got to security settings in bios and disable wlan, boot to windows, shut down, boot to bios, enable wlan, save and boot to windows and hopefully it would work.

i recommend either DW1560, a BCM4360CS2/2CS (which ever is cheaper) with an adapter or DW1820A with taping technique (which I use).

**Comment by c3o8k1g** [comment]
Thanks for your incredibly fast reply.
I understand the differences between your P50 and my P52.
However, I tried to contact you anyway, especially regarding the driver.

**Comment by midi1996** [comment]
hmmm. Sorry man, you can see if the same thing happen with other OSes, no idea if that's a windows thing or a card issue. You can try downgrading the driver version if that's possible.

**Comment by c3o8k1g** [comment]
That's the funny thing. In macOS everything works smoothly (even though it detects fewer networks).
Do you by any chance have a link to the download page for the driver you use?

**Comment by c3o8k1g** [comment]
In the case of the P52 no modifications (drilling/dremeling) are required.
I was able to get my hands on a second card. I can confirm it was a faulty part indeed, as originally suggested.
Please, feel free to remove this issue entirely, given that it's not at all related to this repository.
