### ISSUE TITLE
Thunderbolt?

### ISSUE THREAD

**Issue by sorachan** [midi1996/P50-opencore-hackintosh#9]
You wrote in your README.md that you were "successful to make it load up in OS", could you please tell me how you did it?

I'm currently running macOS 12 on my P50 and I'm trying to make Thunderbolt work because I need FireWire, even if that means losing USB after wake (only on the TP/USB-C port or in general?)

**Comment by midi1996** [comment]
Plug your thunderbolt device before booting up your laptop. It should work while it's running but will die and probably kernel panic when you put the laptop to sleep or unplug the device. There is really nothing else to do about it. I tried TbtForcePower but that only does the same as plugging the hardware before booting up. I have no fix right now and the P50 acpi is weird since it's first generation TB3 hardware, we don't even have control over the power states of the chipset like in 8th gen laptops or later, which helps them have easy setup for macos compatibly.

**Comment by sorachan** [comment]
I already tried booting with my Thunderbolt-to-FireWire-to-interface setup connected and Presonus' FireWire drivers installed but my interface doesn't show up… System Report says "Thunderbolt/USB4: No drivers are loaded." USB 3.1 via the TB3/USB-C port works fine.

**Comment by midi1996** [comment]
Seeing No drivers are loaded is normal. Setting it up to look like a mac's
tb3 interface is hard and might require some firmware flashing which I am
not willing to do. That's as far as I got mine.

**Comment by sorachan** [comment]
Oh well, maybe it's just my adapter chain (TB3 > TB2 > FireWire) that doesn't work. I'm just gonna return the adapters to the Apple store and shelf my FireWire interface, already got myself a new USB interface which works perfectly. The P50 is a really great HackBook for music stuff! (Got the i7 variant.)
